# Generated by Django 2.2.10 on 2020-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='nombre_clave')),
                ('name', models.CharField(max_length=255, verbose_name='Red social')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Ultima edición')),
            ],
            options={
                'verbose_name': 'enlace social',
                'verbose_name_plural': 'enlaces sociales',
                'ordering': ['name'],
            },
        ),
    ]
