# Generated by Django 2.2.10 on 2020-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_auto_20200508_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Nombre clave'),
        ),
    ]
