# Generated by Django 2.2.10 on 2020-05-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_auto_20200508_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
